### PR TITLE
Make offline feature optional

### LINKED ISSUE #61: Is it possible to disable offline page completely (in the manifold for example)?
I'm aware of hostedwebapp.disableOfflinePage(), but that only loads after deviceready has fired and I'm afraid that if a device is offline it will go to the offline page, before that this function is called.

### PR DESCRIPTION
**Pull request by vjrantal**
The feature can be enabled with mjs_offline_feature property in the
manifest.json file.

Fixes #61.

### CODE REVIEW

**Comment by boyofgreen** [comment]
Hi @vjrantal ,
  Thank you for the pull request.  From the code it looks like this would disable to offline page by default, I think we would want to enable by default and allow a parameter to turn it off if you don't want it.  right?

**Comment by vjrantal** [comment]
@boyofgreen: You are right that I initially changed the feature to be opt-in (ref: https://github.com/manifoldjs/ManifoldCordova/issues/61#issuecomment-211862291).

If it is preferred to be opt-out, I will amend the commit.

I guess I was just wondering how many would ship an app to production with the default offline page? Or, would it be that if someone wants to leverage this feature, they'd anyways do some tweaks for the offline page and it wouldn't maybe then be too bad to also add a custom manifest.json property (i.e., explicitly opt-in for the feature)?

Also, if someone wants to invest into good offline behavior, would they want to leverage Application Cache or Service Workers? If that would be the case, then the developer would always have to remember to disable the ManifoldJS offline feature first (in case it would be opt-out).

**Comment by boyofgreen** [comment]
What you are saying is actually a good stratigy, but what I would like to do is start by adding it with it on, and get people use to the idea that there is a switch.  Then in a future release we can turn it off by default.  We need to do a bit of education first, honestly, most folks do just use the default (and sometimes dress it up a bit), and I don't ever want there to be a Manifoldjs app that gives a 404 to users :|   if you can make the adjustment, I would be greatful, we want to start testing this next release the week after next.
Thanks,
Jeff

**Comment by boyofgreen** [comment]
also, can you do the pull request to the v0.3 branch.  Sorry about that.

**Comment by vjrantal** [comment]
@boyofgreen: What you say above makes sense. Will close this one and make the changes as proposed.

**Pull request closed without merging**
